name: Deploy to  dev.pratics.com.br com ssh
on: 
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout do repositorio
      uses: actions/checkout@v1
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          TARGET: "/home2/prat9515/" 
          PORT: "2222"
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvOz --delete"
          SOURCE: "public_html/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "dev.pratics.com.br"
